# Air configuration for golang-base
# Builds the server from cmd/server and runs the resulting binary

[build]
  # Build command: build binary into tmp/main from the server package
  cmd = "go build -o tmp/main ./cmd/server"
  # The built binary that Air will run
  bin = "tmp/main"
  # Directories and extensions to watch
  include_dir = ["cmd", "internal", "migrations"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Exclude temporary and VCS directories
  exclude_dir = ["tmp", "vendor", ".git"]
  # Build delay in milliseconds
  delay = 500

[log]
  time = true
  color = true
