# Air configuration file for golang-base project
# See https://github.com/air-verse/air for full documentation

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Array of commands to run before each build
  pre_cmd = []
  # Just plain old shell command. You could use `make` as well.
  cmd = "go build -o ./tmp/main ./cmd/server"
  # Array of commands to run after ^C
  post_cmd = []
  # Binary file yields from `cmd`.
  bin = "tmp/main"
  # Customize binary, can setup environment variables when run your app.
  full_bin = "APP_ENV=development ./tmp/main"
  # Watch these filename extensions.
  include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "env"]
  # Ignore these filename extensions or directories.
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "bin", "docs", "migrations", "ssl", ".git", "node_modules"]
  # Watch these directories if you specified.
  include_dir = []
  # Watch these files.
  include_file = []
  # Exclude files.
  exclude_file = []
  # Exclude unchanged files.
  exclude_unchanged = false
  # Follow symlink for directories
  follow_symlink = false
  # This log file places in your tmp_dir.
  log = "errors.log"
  # Poll files for changes instead of using fsnotify.
  poll = false
  # Poll interval (defaults to the minimum interval of 500ms).
  poll_interval = 500 # ms
  # It's not necessary to trigger build each time file changes if it's too frequent.
  delay = 0 # ms
  # Stop running old binary when build errors occur.
  stop_on_error = false
  # Send Interrupt signal before killing process (windows does not support this feature)
  send_interrupt = false
  # Delay after sending Interrupt signal
  kill_delay = "0s"
  # Rerun binary or not
  rerun = true
  # Delay after each executation
  rerun_delay = 500
  # Add additional arguments when running binary (bin/full_bin). Will run './tmp/main hello world'.
  args_bin = []

[color]
  # Customize each part's color. If no color found, use the raw app log.
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[log]
  # Show log time
  time = false
  # Only show main log (hide build log)
  main_only = false

[misc]
  # Delete tmp directory on exit
  clean_on_exit = false

[screen]
  # Clear screen on rebuild
  clear_on_rebuild = false
  # Enable to keep scroll
  keep_scroll = true