run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - revive
    - gofmt
    - goimports
    - misspell
    - errcheck
    - deadcode

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
