# Configuration file for the project

app:
  name: golang-base
  env: development

database:
  driver: postgres
  dsn: "host=localhost port=5432 user=postgres password=postgres dbname=golang_base sslmode=disable"
