services:
  db:
    image: postgres:15-alpine
    container_name: golang_base_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-appdb}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: golang_base_redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: golang_base_app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      APP_PORT: ${APP_PORT:-8080}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-appdb}
      DB_SSLMODE: disable
      REDIS_ADDR: redis:6379
    ports:
      - "8080:8080"

volumes:
  db_data:

